#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
# -------- package management
- include_tasks: apt.yml
- include_tasks: pip.yml

# -------- docker setup
- include_tasks: docker.yml

# -------- log forwarding support
- include_tasks: logstash.yml
  when: syslog_remote_server is defined

# -------- configure basic iptables rules
- include_tasks: iptables.yml

# -------- configure timesync
- include_tasks: timesync.yml

# -------- Install local ssl root certificate
- include_tasks: certificates.yml
  when: ssl_root_certificate_pem is defined

# -------- default user operations 
- include_tasks: users.yml