---
- name: Install systemd-timesyncd
  apt:
    name: systemd-timesyncd
    state: present

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"
  notify: systemd-timesyncd configuration changed

- name: Configure systemd-timesyncd
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
    owner: root
    group: root
  notify: systemd-timesyncd configuration changed

- name: Start and enable systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    enabled: yes
    state: started