#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: reload unit files
  command: systemctl daemon-reload

- name: restart syslog-ng
  action: service name=syslog-ng state=restarted enabled=yes

- name: restart journald
  action: service name=systemd-journald state=restarted enabled=yes

- name: restart docker
  action: service name=docker state=restarted enabled=yes

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd.service
    state: restarted
  listen: systemd-timesyncd configuration changed

- name: Write adjtime
  command: hwclock --systohc
  when: ansible_virtualization_role == "host" or ansible_virtualization_role == "NA"
  listen: systemd-timesyncd configuration changed
