---
- name: Ensure OpenSSL is installed
  tdnf: 
    name: openssl 
    state: present

- name: Copy root certificate to store
  copy:
    content: "{{ ssl_root_certificate_pem }}"
    dest: /etc/ssl/certs/{{ ssl_root_certificate_pem_filename }} 
    owner: root
    group: root
    mode: "0644"
    backup: yes
  register: cert_installed

- name: Compile new certificate into store
  command: rehash_ca_certificates.sh
  when: cert_installed.changed