#
# Default settings for IPTables
#

---
- name: Install the `iptables` package
  tdnf:
    name: iptables
    state: latest

- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
    state: present

- name: Firewall rule - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present

- name: Firewall rule - allow port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
    state: present

- name: Firewall rule - allow port 22/SSH traffic
  iptables:
    chain: INPUT
    destination_port: '22'
    jump: ACCEPT
    protocol: tcp
    state: present

- name: Firewall rule - allow port 80/HTTP traffic
  iptables:
    chain: INPUT
    destination_port: '80'
    jump: ACCEPT
    protocol: tcp
    state: present

- name: Firewall rule - allow port 443/HTTPS traffic
  iptables:
    chain: INPUT
    destination_port: '443'
    jump: ACCEPT
    protocol: tcp
    state: present

- name: save iptables
  shell: "iptables-save > /etc/systemd/scripts/ip4save"
  become: true
  changed_when: false